# Generated by Django 5.2 on 2025-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_db',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=10000)),
                ('activation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tokens_db',
            fields=[
                ('access_token', models.CharField(max_length=10000, unique=True)),
                ('identity', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userFields',
            fields=[
                ('identity', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('fields', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='verificationSystem',
            fields=[
                ('identity', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('ActivationCode', models.CharField(max_length=8)),
            ],
        ),
    ]
