# Generated by Django 5.2 on 2025-05-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_session_id_chatmessage_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
